from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "config" / "electrical_codebook.json"
DEFAULT_OUTPUTS = (
    ROOT / "firmware" / "worldblocks_mega_sensing" / "generated_codebook.h",
)


def render_header(source: Path) -> str:
    data = json.loads(source.read_text(encoding="utf-8"))
    codes = data["codes"]
    rows = "\n".join(
        f'  {{"{item["id"]}", {float(item["nominal_ohms"]):.1f}f, '
        f'{float(item["target_g_us"]):.6f}f}},'
        for item in codes
    )
    return f"""// Generated by tools/generate_firmware_codebook.py. Do not edit.
#pragma once

#include <Arduino.h>

struct ElectricalCode {{
  const char *id;
  float nominalOhms;
  float targetGUs;
}};

const char ELECTRICAL_CODEBOOK_ID[] = "{data['id']}";
const uint8_t ELECTRICAL_CODE_COUNT = {len(codes)};
const ElectricalCode ELECTRICAL_CODES[ELECTRICAL_CODE_COUNT] = {{
{rows}
}};
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the AVR electrical codebook header")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, action="append")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_header(args.input)
    outputs = tuple(args.output) if args.output else DEFAULT_OUTPUTS
    for output in outputs:
        if args.check:
            if not output.exists() or output.read_text(encoding="utf-8") != rendered:
                raise SystemExit(f"generated header is stale: {output}")
            continue
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
