from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "config" / "one_module_channel_mapping.json"
DEFAULT_OUTPUT = (
    ROOT / "firmware" / "worldblocks_mega_sensing" / "generated_channel_map.h"
)
COLUMN_RE = re.compile(r"^(L0(?:\.5)?)-r([01])-c([0-3])$")


def render_header(source: Path) -> str:
    data = json.loads(source.read_text(encoding="utf-8"))
    columns = data["columns"]
    expected_ids = [
        f"{layer}-r{row}-c{col}"
        for layer in ("L0", "L0.5")
        for row in range(2)
        for col in range(4)
    ]
    column_ids = [str(item["column_id"]) for item in columns]
    channels = [int(item["channel"]) for item in columns]
    if column_ids != expected_ids or any(not COLUMN_RE.fullmatch(item) for item in column_ids):
        raise ValueError("columns must contain all 16 logical IDs in row-major order")
    if sorted(channels) != list(range(16)):
        raise ValueError("physical channels must be a permutation of 0 through 15")
    rows = ", ".join(str(channel) for channel in channels)
    return f"""// Generated by tools/generate_firmware_channel_map.py. Do not edit.
#pragma once

#include <Arduino.h>

const char CHANNEL_MAPPING_ID[] = "{data['id']}";
const uint8_t PHYSICAL_CHANNEL_BY_COLUMN[16] = {{{rows}}};
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the one-module mux map header")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_header(args.input)
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"generated header is stale: {args.output}")
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
