// Generated by tools/generate_firmware_channel_map.py. Do not edit.
#pragma once

#include <Arduino.h>

const char CHANNEL_MAPPING_ID[] = "shared-module-order-calibrated-2026-07-24";
const uint8_t PHYSICAL_CHANNEL_BY_COLUMN[16] = {1, 5, 9, 13, 0, 4, 8, 12, 3, 7, 11, 15, 2, 6, 10, 14};
