// Generated by tools/generate_firmware_codebook.py. Do not edit.
#pragma once

#include <Arduino.h>

struct ElectricalCode {
  const char *id;
  float nominalOhms;
  float targetGUs;
};

const char ELECTRICAL_CODEBOOK_ID[] = "e96-2026-07-19";
const uint8_t ELECTRICAL_CODE_COUNT = 6;
const ElectricalCode ELECTRICAL_CODES[ELECTRICAL_CODE_COUNT] = {
  {"C0", 8250.0f, 121.212121f},
  {"C1", 9760.0f, 102.459016f},
  {"C2", 12400.0f, 80.645161f},
  {"C3", 16500.0f, 60.606061f},
  {"C4", 24900.0f, 40.160643f},
  {"C5", 49900.0f, 20.040080f},
};
